spring:
  datasource:
    url:
    username:
    password:
    type: org.apache.tomcat.jdbc.pool.DataSource

  flyway:
    enabled: true
    clean-disabled: true

  jpa:
    properties:
      org.hibernate.envers.global_with_modified_flag: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        hbm2ddl:
          delimiter: ';'
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: INFO
    io.apm: INFO
    org.springframework: WARN
    org.hibernate: WARN
    com.amazonaws: WARN
    org.quartz: INFO
    org.springframework.boot.web.embedded.tomcat.TomcatWebServer: INFO
    org.apache.tomcat.jdbc: DEBUG


security:
  oauth2:
    authorization:
      accessTokenValidity: 300
      refreshTokenValidity: 300
    resource:
      jwt:
        key-value:

server:
  servlet:
    context-path: /api

exception:
  message:
    supportedLanguages: en

http:
  ssl:
    keyStorePath:
    keyPassword:
    storePassword: ${http.ssl.keyPassword}
