spring:
  datasource:
    url: postgres://vtedrihspdaqub:705a74baf790ab29b6ed91c0d5648a812ccd6dcb6a0dd69e0580a82d1ec43a53@ec2-46-137-84-140.eu-west-1.compute.amazonaws.com:5432/dpp7g1l7vk1oq
    username: vtedrihspdaqub
    password: 705a74baf790ab29b6ed91c0d5648a812ccd6dcb6a0dd69e0580a82d1ec43a53
    type: org.apache.tomcat.jdbc.pool.DataSource

  flyway:
    enabled: true
    clean-disabled: false
#    baselineOnMigrate: true

  jpa:
    properties:
      org.hibernate.envers.global_with_modified_flag: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        hbm2ddl:
          delimiter: ';'
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: INFO
    io.apm: INFO
    org.springframework: WARN
    org.hibernate: WARN
    com.amazonaws: WARN
    org.quartz: INFO
    org.springframework.boot.web.embedded.tomcat.TomcatWebServer: INFO
    org.apache.tomcat.jdbc: DEBUG


security:
  oauth2:
    resource:
      jwt:
        key-value:

server:
  servlet:
    context-path: /api


cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    region:
      static: eu-west-1
      auto: false
    s3:
      bucketName:
      preUrlExpireTime: 15 # minutes
    stack:
      auto: false

exception:
  message:
    supportedLanguages: en

apm:
  url:
  authUrl:
  ipnUrl:
  clientId:
  clientSecret:
  admin-client-id:
  admin-client-secret:
