spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

  jpa:
    properties:
      #      javax.persistence.schema-generation.scripts.action: create
      #      javax.persistence.schema-generation.scripts.create-target: src/main/resources/sql/create.sql
      hibernate:
        hbm2ddl:
          delimiter: ';'
        jpa:
          compliance:
            global_id_generators: false
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    clean-disabled: false
    baselineOnMigrate: true

  thymeleaf:
    enabled: true
    cache: false
    check-template: true
    check-template-location: true
    mode: HTML5
    encoding: UTF-8
    suffix: .html
    prefix: classpath:/mail/


security:
  oauth2:
    resource:
      jwt:
        key-value: 123456

server:
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    io.apm: INFO
    org.springframework: WARN
    org.hibernate: WARN
    com.amazonaws: WARN
    org.quartz: INFO
    org.springframework.boot.web.embedded.tomcat.TomcatWebServer: INFO
    org.apache.tomcat.jdbc: DEBUG

email:
  sendgrid:
    apiKey: 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
    url: https://api.sendgrid.com/v3/Notification/send
    from: info.dictionary@yandex.ru


system:
  urls:
    operatorPasswordRecovery: https://local-ledger.fingates.net/admin/create-password
